version: '3.9'

x-base:
  &base
  env_file:
    - ./.env
  restart: always
  networks:
    - url-shortener

services:
   db:
    <<: *base
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASS}
    volumes:
      - db_data:/var/lib/mysql
    expose:
      - 3306
    
    
   redis:
    <<: *base
    image: redis:latest
    container_name: redis
    volumes:
    - redis_data:/data
    expose:
      - 6319
    depends_on:
      - db


   backend:
    <<: *base
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "80:8000"
    depends_on:
      - db
      - redis

volumes:
  db_data:
  redis_data:

networks:
  url-shortener: